#!/bin/bash
lsblk	# lists all available storage devices
sudo eject /dev/sdb	# used to eject the device (/dev/sdb)
umount /dev/sdb1	# unmount the usb disk
echo 'start=2048, type=83' | sudo sfdisk /dev/sdb1	
sudo mkfs.ext4 /dev/sdb1
